automation:
  refresh_minutes: 30
mam:
  auto_purchase:
    upload: true
    vip: true
    wedge: true
  buffer: 52000
  dont_spend_below: 50000
  mam_id: DcjvP0n1IDx1cjiiT-Qq0lGC3aBDOEAUW_f_UaDsY558pky9_z5IPJZIpooSOB6GKZ7txY7JNWcDNJXf3rtI_GAiF5CiTCHwkJrfj0Jffmo8G6SAfyYXQ62pej2iHpubnXKVESSWDptpf_2DbfJVPqOhoWsyP_QuG2QgdeURePtEFVRheDxF1QZU1-icDvz5WgqBJNc54YdbPIJ_h8MelleyYzUdu60MVoqxHQQxcvMuvwUywCxPzQUpKA8brRu4e3zc-_bkUUpqTRJKm7HtNXeunpuTlwUGOoot
  min_points: 55000
  session_type: asn
  wedge_hours: 168
mam_ip: ''
notifications:
  email:
    enabled: false
    events:
      cookie_updated: true
      ip_changed: true
      points_below_threshold: true
      wedge_purchase: true
    smtp:
      password: ''
      port: 587
      recipient: ''
      sender: ''
      server: ''
      username: ''
  webhooks: []
vpn_ip: 68.235.35.124:47430
